#!/bin/bash

# =============================================================================
# White-Label App Clone Script
# =============================================================================
# This script creates a new mobile app from the Property Rental template.
# It handles all the necessary file updates for rebranding.
#
# Usage: ./scripts/clone-app.sh <new-app-name> <new-app-id> [target-directory]
#
# Example: ./scripts/clone-app.sh "Beach Rentals" 39 ~/projects/beach-rentals
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored output
print_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check arguments
if [ $# -lt 2 ]; then
    echo "Usage: $0 <new-app-name> <new-app-id> [target-directory]"
    echo ""
    echo "Arguments:"
    echo "  new-app-name     Display name for the app (e.g., 'Beach Rentals')"
    echo "  new-app-id       App ID from the admin portal (e.g., 39)"
    echo "  target-directory Optional. Where to create the new app (default: ../\$app_name_snake)"
    echo ""
    echo "Example:"
    echo "  $0 'Beach Rentals' 39"
    echo "  $0 'Mountain Cabins' 40 ~/projects/mountain-cabins"
    exit 1
fi

NEW_APP_NAME="$1"
NEW_APP_ID="$2"

# Convert app name to different formats
APP_NAME_SNAKE=$(echo "$NEW_APP_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -cd '[:alnum:]_')
APP_NAME_KEBAB=$(echo "$NEW_APP_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
APP_NAME_PASCAL=$(echo "$NEW_APP_NAME" | sed 's/[^a-zA-Z0-9]/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1' | tr -d ' ')

# Target directory
if [ -n "$3" ]; then
    TARGET_DIR="$3"
else
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SOURCE_DIR="$(dirname "$SCRIPT_DIR")"
    TARGET_DIR="$(dirname "$SOURCE_DIR")/$APP_NAME_SNAKE"
fi

# Source directory (this app)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$(dirname "$SCRIPT_DIR")"

echo ""
echo "=============================================="
echo "  White-Label App Clone Script"
echo "=============================================="
echo ""
echo "New App Name:    $NEW_APP_NAME"
echo "App ID:          $NEW_APP_ID"
echo "Package Name:    $APP_NAME_KEBAB"
echo "Module Name:     $APP_NAME_PASCAL"
echo "Source:          $SOURCE_DIR"
echo "Target:          $TARGET_DIR"
echo ""

# Confirm
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

# Check if target exists
if [ -d "$TARGET_DIR" ]; then
    print_error "Target directory already exists: $TARGET_DIR"
    exit 1
fi

# Step 1: Copy the project
print_step "Copying project files..."
cp -r "$SOURCE_DIR" "$TARGET_DIR"
print_success "Project copied to $TARGET_DIR"

# Step 2: Remove git history and node_modules
print_step "Cleaning up..."
rm -rf "$TARGET_DIR/.git"
rm -rf "$TARGET_DIR/node_modules"
rm -rf "$TARGET_DIR/ios/Pods"
rm -rf "$TARGET_DIR/ios/build"
rm -rf "$TARGET_DIR/android/build"
rm -rf "$TARGET_DIR/android/app/build"
rm -rf "$TARGET_DIR/.env"
print_success "Cleaned up git history and build artifacts"

# Step 3: Update package.json
print_step "Updating package.json..."
sed -i '' "s/\"name\": \".*\"/\"name\": \"$APP_NAME_KEBAB\"/" "$TARGET_DIR/package.json"
print_success "Updated package.json"

# Step 4: Update app.json
print_step "Updating app.json..."
cat > "$TARGET_DIR/app.json" << EOF
{
  "name": "$APP_NAME_PASCAL",
  "displayName": "$NEW_APP_NAME"
}
EOF
print_success "Updated app.json"

# Step 5: Create .env file
print_step "Creating .env file..."
cat > "$TARGET_DIR/.env" << EOF
# =============================================================================
# $NEW_APP_NAME - Environment Configuration
# =============================================================================
# Generated by clone-app.sh on $(date)

# App Configuration
APP_ID=$NEW_APP_ID
APP_NAME=$APP_NAME_PASCAL
APP_DISPLAY_NAME=$NEW_APP_NAME

# API Configuration
API_BASE_URL=http://localhost:3000/api/v1
API_TIMEOUT=30000

# Server Configuration  
SERVER_URL=http://localhost:3000

# Feature Flags
ENABLE_ANALYTICS=false
ENABLE_CRASH_REPORTING=false
DEBUG_MODE=true

# iOS Configuration
IOS_BUNDLE_ID=com.bluestoneapps.$APP_NAME_SNAKE

# Android Configuration
ANDROID_PACKAGE=com.bluestoneapps.$APP_NAME_SNAKE
EOF
print_success "Created .env file"

# Step 6: Update iOS display name
print_step "Updating iOS configuration..."
if [ -f "$TARGET_DIR/ios/PropertyListings/Info.plist" ]; then
    # Update CFBundleDisplayName
    sed -i '' "s/<string>Property Rental<\/string>/<string>$NEW_APP_NAME<\/string>/" "$TARGET_DIR/ios/PropertyListings/Info.plist"
    print_success "Updated iOS Info.plist"
else
    print_warning "iOS Info.plist not found - manual update may be needed"
fi

# Step 7: Update Android display name
print_step "Updating Android configuration..."
if [ -f "$TARGET_DIR/android/app/src/main/res/values/strings.xml" ]; then
    sed -i '' "s/<string name=\"app_name\">.*<\/string>/<string name=\"app_name\">$NEW_APP_NAME<\/string>/" "$TARGET_DIR/android/app/src/main/res/values/strings.xml"
    print_success "Updated Android strings.xml"
else
    print_warning "Android strings.xml not found - manual update may be needed"
fi

# Step 8: Update app.config.ts defaults
print_step "Updating app.config.ts..."
if [ -f "$TARGET_DIR/src/config/app.config.ts" ]; then
    sed -i '' "s/APP_ID: [0-9]*/APP_ID: $NEW_APP_ID/" "$TARGET_DIR/src/config/app.config.ts"
    sed -i '' "s/APP_NAME: '.*'/APP_NAME: '$APP_NAME_PASCAL'/" "$TARGET_DIR/src/config/app.config.ts"
    sed -i '' "s/APP_DISPLAY_NAME: '.*'/APP_DISPLAY_NAME: '$NEW_APP_NAME'/" "$TARGET_DIR/src/config/app.config.ts"
    print_success "Updated app.config.ts"
else
    print_warning "app.config.ts not found"
fi

# Step 9: Initialize new git repo
print_step "Initializing new git repository..."
cd "$TARGET_DIR"
git init
git add .
git commit -m "Initial commit: $NEW_APP_NAME (cloned from Property Rental template)"
print_success "Git repository initialized"

# Done!
echo ""
echo "=============================================="
echo "  Clone Complete!"
echo "=============================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Navigate to the new project:"
echo "   cd $TARGET_DIR"
echo ""
echo "2. Install dependencies:"
echo "   npm install"
echo ""
echo "3. Install iOS pods (macOS only):"
echo "   cd ios && pod install && cd .."
echo ""
echo "4. Update the API URL in .env if needed"
echo ""
echo "5. Run the app:"
echo "   npm run ios    # or"
echo "   npm run android"
echo ""
echo "NOTE: For full native renaming (bundle ID, package name),"
echo "consider using react-native-rename:"
echo "   npx react-native-rename \"$NEW_APP_NAME\" -b com.yourcompany.$APP_NAME_SNAKE"
echo ""
print_success "Happy coding!"
